spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/shortcut
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate:
      show-sql: true
      format_sql: true
      hbm2ddl.auto: validate
      jdbc.lob.non_contextual_creation: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org.hibernate.SQL: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springfox:
  documentation:
    swagger.v2.path: /v2/api-docs
jwt:
  secret: malletsecretword
  expired: 3600000